#!/usr/bin/python3
import pygame;
import os;
pygame.mixer.init();

print("Welcome to CitoPlayer 1.0!");
while True:
    com = input("citoplayer> ").split();
    if (com[0] == "play"):
        pygame.mixer.music.load("".join(com[1:]));
        pygame.mixer.music.play();
        print(f"Playing the '{''.join(com[1:])}'");
    elif (com[0] == "test"):
        pygame.mixer.music.load("music/test.mp3");
        pygame.mixer.music.play();
        print("Playing the 'music/test.mp3'");
    elif (com[0] == "stop"):
        pygame.mixer.music.stop();
        print("Stopped the music.");
    elif (com[0] == "pause"):
        pygame.mixer.music.pause();
        print("Paused the music.");
    elif (com[0] == "unpause"):
        pygame.mixer.music.unpause();
        print("Unpaused the music.");
    elif (com[0] == "exit"):
        exit();
    elif (com[0] == "help"):
        print("1. play - play music");
        print("2. test - test of music");
        print("3. stop - stop the music");
        print("4. pause - pause the music");
        print("5. unpause - unpause the music");
        print("6. list - list of all musics");
        print("7. exit - exit");
    elif (com[0] == "list"):
        os.system("ls music/");
    else:
        print("Bad command.");
